export {default as HomePage} from "./HomePage/HomePage"
export {default as CartPage} from "./CartPage/CartPage"
export {default as ProductPage} from "./ProductPage/ProductPage"
export {default as ShopPage} from "./ShopPage/ShopPage"
export {default as ContactPage} from "./ContactPge/ContactPge"